#!/bin/bash

## Only execute if preinst was succesful
if [ -e /opt/android-studio-ide.zip ]; then
  ## Unzip Android Studio's source code
  unzip -qq -o /opt/android-studio-ide.zip -d /opt/

  ## Remove the package zip package at end
  rm -f /opt/android-studio-ide.zip

  ## Give permissions to folder to let the built-in update system work
  chmod ugo+rX -R /opt/android-studio

  ## Update icon caches
  gtk-update-icon-cache /usr/share/icons/hicolor/
  update-desktop-database -q
  xdg-desktop-menu forceupdate
  exit 0
fi
